### ISSUE TITLE
Documentation of expression language for visual rules 

### ISSUE THREAD

**Issue by eercanayar** [awsdocs/aws-iot-twinmaker-docs#2]
There isn't any documentation page explains regarding the expression language of visual rules. 

The following documentation are required at minimum:
- Syntax
- Operators
- Functions
- How are the possibilities and examples

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
